# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureImageBuilderTask@1
  inputs:
    customImageResourceId: '/subscriptions/0f401833-78ff-4ebe-a797-67791c5fbdaa/resourceGroups/Generalized/providers/Microsoft.Compute/images/myImage'
    storageAccountName: 'aibstordot1560287540'
    distributeType: 'vhd'
    ibSubscription: 'VMTesting3(0f401833-78ff-4ebe-a797-67791c5fbdaa)'
    ibAzureResourceGroup: 'Generalized'
    ibLocation: 'westcentralus'